spring:
  application:
    name: visitas

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 3000ms
          max-interval: 10000ms
          multiplier: 2.0
          max-retries: 3



  jpa:

    hibernate:
        ddl-auto: validate

    show-sql: true
    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8085
